[opener]
edit = [{ run = "nvim %s", block = true, desc = "Edit with neovim." }]

[[plugin.prepend_fetchers]]
group = "git"
run = "git"
url = "*"

[[plugin.prepend_fetchers]]
group = "git"
run = "git"
url = "*/"
