[opener]
edit = [
  { run = 'nvim "$@"', block = true, desc = "Edit with neovim.", for = "unix" },
  { run = 'nvim %*', block = true, desc = "Edit with neovim.", for = "windows" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
